INSERT INTO users (username, password, first_name, last_name, email) 
VALUES  ('testuser',
        'testpassword', 
        'Test', 
        'User', 
        'testuser@comeawayapp.com');

INSERT INTO days (day)
VALUES  ('1'),
        ('2'),
        ('3'),
        ('4'),
        ('5'),
        ('6'),
        ('7'),
        ('8'),
        ('9'),
        ('10'),
        ('11'),
        ('12'),
        ('13'),
        ('14'),
        ('15'),
        ('16'),
        ('17'),
        ('18'),
        ('19'),
        ('20'),
        ('21'),
        ('22'),
        ('23'),
        ('24'),
        ('25'),
        ('26'),
        ('27'),
        ('28'),
        ('29'),
        ('30'),
        ('31');

INSERT INTO days_of_week (day_of_week)
VALUES  ('Sunday'),
        ('Monday'),
        ('Tuesday'),
        ('Wednesday'),
        ('Thursday'),
        ('Friday'),
        ('Saturday');

INSERT INTO months (month)
VALUES  ('January'),
        ('February'),
        ('March'),
        ('April'),
        ('May'),
        ('June'),
        ('July'),
        ('August'),
        ('September'),
        ('October'),
        ('November'),
        ('December');

INSERT INTO years (year)
VALUES  ('2023'),
        ('2024'),
        ('2025'),
        ('2026'),
        ('2027'),
        ('2028'),
        ('2029'),
        ('2030'),
        ('2031'),
        ('2032'),
        ('2033'),
        ('2034'),
        ('2035'),
        ('2036'),
        ('2037'),
        ('2038'),
        ('2039'),
        ('2040'),
        ('2041'),
        ('2042'),
        ('2043'),
        ('2044'),
        ('2045'),
        ('2046'),
        ('2047'),
        ('2048'),
        ('2049'),
        ('2050');